import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from './components/Provider'
import { Header } from './components/header/Header'
import style from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const styeClass = [inter.className, style.main].join(' ')
  return (
    <html lang='en'>
      <body>
        <Provider>
          <main className={styeClass}>{children}</main>
        </Provider>
      </body>
    </html>
  )
}
